package com.thoughtinput.capture.ui.theme

import androidx.compose.ui.graphics.Color

val ThoughtPrimary = Color(0xFF6750A4)
val ThoughtOnPrimary = Color(0xFFFFFFFF)
val ThoughtPrimaryContainer = Color(0xFFEADDFF)
val ThoughtOnPrimaryContainer = Color(0xFF21005D)
val ThoughtSecondary = Color(0xFF625B71)
val ThoughtOnSecondary = Color(0xFFFFFFFF)
val ThoughtBackground = Color(0xFFFFFBFE)
val ThoughtOnBackground = Color(0xFF1C1B1F)
val ThoughtSurface = Color(0xFFFFFBFE)
val ThoughtOnSurface = Color(0xFF1C1B1F)
val ThoughtSurfaceVariant = Color(0xFFE7E0EC)
val ThoughtOnSurfaceVariant = Color(0xFF49454F)
val ThoughtSurfaceContainerHigh = Color(0xFFECE6F0)
val ThoughtOutline = Color(0xFF79747E)
val ThoughtError = Color(0xFFB3261E)
val ThoughtOnError = Color(0xFFFFFFFF)

val ThoughtPrimaryDark = Color(0xFFD0BCFF)
val ThoughtOnPrimaryDark = Color(0xFF381E72)
val ThoughtPrimaryContainerDark = Color(0xFF4F378B)
val ThoughtOnPrimaryContainerDark = Color(0xFFEADDFF)
val ThoughtSecondaryDark = Color(0xFFCCC2DC)
val ThoughtOnSecondaryDark = Color(0xFF332D41)
val ThoughtBackgroundDark = Color(0xFF1C1B1F)
val ThoughtOnBackgroundDark = Color(0xFFE6E1E5)
val ThoughtSurfaceDark = Color(0xFF1C1B1F)
val ThoughtOnSurfaceDark = Color(0xFFE6E1E5)
val ThoughtSurfaceVariantDark = Color(0xFF49454F)
val ThoughtOnSurfaceVariantDark = Color(0xFFCAC4D0)
val ThoughtSurfaceContainerHighDark = Color(0xFF2B2930)
val ThoughtOutlineDark = Color(0xFF938F99)
val ThoughtErrorDark = Color(0xFFF2B8B5)
val ThoughtOnErrorDark = Color(0xFF601410)
